import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'English (US)' | 'English (UK)' | 'Español' | 'Français' | 'Deutsch' | '日本語';

interface LanguageContextType {
  language: Language;
  timezone: string;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LANGUAGE_CONFIG: Record<Language, { timezone: string; translations: Record<string, string> }> = {
  'English (US)': { 
    timezone: 'Pacific Time (PT)',
    translations: {
      dashboard: 'Dashboard',
      tasks: 'Tasks',
      notes: 'Notes',
      calendar: 'Calendar',
      settings: 'Settings',
      profile: 'Profile',
      security: 'Security',
      language: 'Language',
      save: 'Save Changes',
      reset: 'Reset via Email',
      bio: 'Bio',
      name: 'Full Name',
      email: 'Email Address',
      email_readonly_hint: 'Email is tied to your login and cannot be edited here.',
      welcome: 'Welcome back, Alex',
      search: 'Search',
      signout: 'Sign Out',
      interface_lang: 'Interface Language',
      date_time: 'Date & Time',
      timezone: 'Timezone',
      timezone_sync: 'Timezone is automatically synchronized with your language selection.',
      lang_update_note: 'Changing language settings will update the entire interface. Some content may remain in its original language.',
      good_morning: 'Good morning',
      good_afternoon: 'Good afternoon',
      good_evening: 'Good evening',
      start_focus: 'Start Focus Session',
      close_focus: 'Close focus',
      focus_session: 'Focus session',
      focus_session_hint: 'Choose a mode, then press play on the timer when you are ready.',
      today_agenda: 'Today\'s Agenda',
      open_calendar: 'Open Full Calendar',
      recent_notebooks: 'Recent Notebooks',
      view_library: 'View Library',
      productivity_tip: 'Daily Productivity Tip',
      tip_text: 'Review your notes within 24 hours to improve long-term retention by up to 80%.',
      tasks_title: 'Tasks',
      tasks_subtitle: 'Organize your academic flow with precision.',
      new_task: 'New Task',
      todo: 'To-Do',
      started: 'Started',
      done: 'Done',
      add_task: 'Add Task',
      title: 'Title',
      description: 'Description',
      due_date: 'Due Date',
      importance: 'Importance',
      create_task: 'Create Task',
      what_needs_done: 'What needs to be done?',
      add_details: 'Add some details...',
      started_on: 'Started on',
      finished_on: 'Finished on',
      notes_title: 'Notes',
      notes_subtitle: 'Organize your thoughts and ideas.',
      search_notes: 'Search notes...',
      recent_folders: 'Recent Folders',
      todays: 'Todays',
      this_week: 'This Week',
      this_month: 'This Month',
      new_folder: 'New folder',
      my_notes: 'My Notes',
      new_note: 'New Note',
      notebooks: 'Notebooks',
      pages: 'Pages',
      manage_notebooks: 'Manage your notebooks and documents.',
      upload_pdf: 'Upload PDF',
      new_notebook: 'New Notebook',
      documents: 'Documents',
      no_notebooks: 'No notebooks in this folder yet.',
      untitled_page: 'Untitled Page',
      untitled_note: 'Untitled Note',
      delete_note_confirm: 'Are you sure you want to delete this note?',
      delete_page_confirm: 'Are you sure you want to delete this page?',
      delete_notebook_confirm: 'Are you sure you want to delete this notebook and all its pages?',
      enter_notebook_title: 'Enter new notebook title:',
      type_something: 'Type something...',
      add_image: 'Add Image',
      add_h1: 'Heading 1',
      add_h2: 'Heading 2',
      add_h3: 'Heading 3',
      add_bullet: 'Bullet List',
      add_number: 'Numbered List',
      add_todo: 'To-Do List',
      list_item: 'List item',
      todo_item: 'To-do item',
      last_edited: 'Last edited',
      tools: 'Tools',
      text: 'Text',
      month: 'Month',
      week: 'Week',
      day: 'Day',
      today: 'Today',
      add_event: 'Add Event',
      event_title: 'Event Title',
      duration: 'Duration',
      tags: 'Tags',
      cancel: 'Cancel',
      new_tag: 'New Tag',
      tag_name: 'Tag name',
      save_label: 'Save',
      location: 'Location',
      add_location: 'Add location',
      all_day: 'All Day',
      add_description: 'Add description',
      create_event: 'Create Event',
      empty_day: 'Your day is empty',
      downtime_message: 'Downtime—recharge complete.',
      time_utilized_message: 'Time well utilized!',
      two_hours_ago: '2h ago',
      quote: '"The secret of getting ahead is getting started."',
      author: '— Mark Twain'
    }
  },
  'English (UK)': { 
    timezone: 'Greenwich Mean Time (GMT)',
    translations: {
      dashboard: 'Dashboard',
      tasks: 'Tasks',
      notes: 'Notes',
      calendar: 'Calendar',
      settings: 'Settings',
      profile: 'Profile',
      security: 'Security',
      language: 'Language',
      save: 'Save Changes',
      reset: 'Reset via Email',
      bio: 'Bio',
      name: 'Full Name',
      email: 'Email Address',
      email_readonly_hint: 'Email is tied to your login and cannot be edited here.',
      welcome: 'Welcome back, Alex',
      search: 'Search',
      signout: 'Sign Out',
      interface_lang: 'Interface Language',
      date_time: 'Date & Time',
      timezone: 'Timezone',
      timezone_sync: 'Timezone is automatically synchronized with your language selection.',
      lang_update_note: 'Changing language settings will update the entire interface. Some content may remain in its original language.',
      good_morning: 'Good morning',
      good_afternoon: 'Good afternoon',
      good_evening: 'Good evening',
      start_focus: 'Start Focus Session',
      close_focus: 'Close focus',
      focus_session: 'Focus session',
      focus_session_hint: 'Choose a mode, then press play on the timer when you are ready.',
      today_agenda: 'Today\'s Agenda',
      open_calendar: 'Open Full Calendar',
      recent_notebooks: 'Recent Notebooks',
      view_library: 'View Library',
      productivity_tip: 'Daily Productivity Tip',
      tip_text: 'Review your notes within 24 hours to improve long-term retention by up to 80%.',
      tasks_title: 'Tasks',
      tasks_subtitle: 'Organize your academic flow with precision.',
      new_task: 'New Task',
      todo: 'To-Do',
      started: 'Started',
      done: 'Done',
      add_task: 'Add Task',
      title: 'Title',
      description: 'Description',
      due_date: 'Due Date',
      importance: 'Importance',
      create_task: 'Create Task',
      what_needs_done: 'What needs to be done?',
      add_details: 'Add some details...',
      started_on: 'Started on',
      finished_on: 'Finished on',
      notes_title: 'Notes',
      notes_subtitle: 'Organize your thoughts and ideas.',
      search_notes: 'Search notes...',
      recent_folders: 'Recent Folders',
      todays: 'Todays',
      this_week: 'This Week',
      this_month: 'This Month',
      new_folder: 'New folder',
      my_notes: 'My Notes',
      new_note: 'New Note',
      notebooks: 'Notebooks',
      pages: 'Pages',
      manage_notebooks: 'Manage your notebooks and documents.',
      upload_pdf: 'Upload PDF',
      new_notebook: 'New Notebook',
      documents: 'Documents',
      no_notebooks: 'No notebooks in this folder yet.',
      untitled_page: 'Untitled Page',
      untitled_note: 'Untitled Note',
      delete_note_confirm: 'Are you sure you want to delete this note?',
      delete_page_confirm: 'Are you sure you want to delete this page?',
      delete_notebook_confirm: 'Are you sure you want to delete this notebook and all its pages?',
      enter_notebook_title: 'Enter new notebook title:',
      type_something: 'Type something...',
      add_image: 'Add Image',
      add_h1: 'Heading 1',
      add_h2: 'Heading 2',
      add_h3: 'Heading 3',
      add_bullet: 'Bullet List',
      add_number: 'Numbered List',
      add_todo: 'To-Do List',
      list_item: 'List item',
      todo_item: 'To-do item',
      last_edited: 'Last edited',
      tools: 'Tools',
      text: 'Text',
      month: 'Month',
      week: 'Week',
      day: 'Day',
      today: 'Today',
      add_event: 'Add Event',
      event_title: 'Event Title',
      duration: 'Duration',
      tags: 'Tags',
      cancel: 'Cancel',
      new_tag: 'New Tag',
      tag_name: 'Tag name',
      save_label: 'Save',
      location: 'Location',
      add_location: 'Add location',
      all_day: 'All Day',
      add_description: 'Add description',
      create_event: 'Create Event',
      empty_day: 'Your day is empty',
      downtime_message: 'Downtime—recharge complete.',
      time_utilized_message: 'Time well utilized!',
      two_hours_ago: '2h ago',
      quote: '"The secret of getting ahead is getting started."',
      author: '— Mark Twain'
    }
  },
  'Español': { 
    timezone: 'Central European Time (CET)',
    translations: {
      dashboard: 'Tablero',
      tasks: 'Tareas',
      notes: 'Notas',
      calendar: 'Calendario',
      settings: 'Ajustes',
      profile: 'Perfil',
      security: 'Seguridad',
      language: 'Idioma',
      save: 'Guardar Cambios',
      reset: 'Restablecer por Correo',
      bio: 'Biografía',
      name: 'Nombre Completo',
      email: 'Correo Electrónico',
      email_readonly_hint: 'El correo está vinculado a tu cuenta y no se puede editar aquí.',
      welcome: 'Bienvenido de nuevo, Alex',
      search: 'Buscar',
      signout: 'Cerrar Sesión',
      interface_lang: 'Idioma de la Interfaz',
      date_time: 'Fecha y Hora',
      timezone: 'Zona Horaria',
      timezone_sync: 'La zona horaria se sincroniza automáticamente con su selección de idioma.',
      lang_update_note: 'Cambiar la configuración de idioma actualizará toda la interfaz. Algunos contenidos pueden permanecer en su idioma original.',
      good_morning: 'Buenos días',
      good_afternoon: 'Buenas tardes',
      good_evening: 'Buenas noches',
      start_focus: 'Iniciar Sesión de Enfoque',
      close_focus: 'Cerrar enfoque',
      focus_session: 'Sesión de enfoque',
      focus_session_hint: 'Elige un modo y pulsa play en el temporizador cuando estés listo.',
      today_agenda: 'Agenda de Hoy',
      open_calendar: 'Abrir Calendario Completo',
      recent_notebooks: 'Cuadernos Recientes',
      view_library: 'Ver Biblioteca',
      productivity_tip: 'Consejo Diario de Productividad',
      tip_text: 'Revise sus notas dentro de las 24 horas para mejorar la retención a largo plazo hasta en un 80%.',
      tasks_title: 'Tareas',
      tasks_subtitle: 'Organiza tu flujo académico con precisión.',
      new_task: 'Nueva Tarea',
      todo: 'Por Hacer',
      started: 'Iniciado',
      done: 'Hecho',
      add_task: 'Agregar Tarea',
      title: 'Título',
      description: 'Descripción',
      due_date: 'Fecha de Entrega',
      importance: 'Importancia',
      create_task: 'Crear Tarea',
      what_needs_done: '¿Qué hay que hacer?',
      add_details: 'Añadir algunos detalles...',
      started_on: 'Iniciado el',
      finished_on: 'Terminado el',
      notes_title: 'Notas',
      notes_subtitle: 'Organiza tus pensamientos e ideas.',
      search_notes: 'Buscar notas...',
      recent_folders: 'Carpetas Recientes',
      todays: 'Hoy',
      this_week: 'Esta Semana',
      this_month: 'Este Mes',
      new_folder: 'Nueva carpeta',
      my_notes: 'Mis Notas',
      new_note: 'Nueva Nota',
      notebooks: 'Cuadernos',
      pages: 'Páginas',
      manage_notebooks: 'Administra tus cuadernos y documentos.',
      upload_pdf: 'Subir PDF',
      new_notebook: 'Nuevo Cuaderno',
      documents: 'Documentos',
      no_notebooks: 'Aún no hay cuadernos en esta carpeta.',
      untitled_page: 'Página sin título',
      untitled_note: 'Nota sin título',
      delete_note_confirm: '¿Estás seguro de que quieres eliminar esta nota?',
      delete_page_confirm: '¿Estás seguro de que quieres eliminar esta página?',
      delete_notebook_confirm: '¿Estás seguro de que quieres eliminar este cuaderno y todas sus páginas?',
      enter_notebook_title: 'Introduce el nuevo título del cuaderno:',
      type_something: 'Escribe algo...',
      add_image: 'Añadir Imagen',
      add_h1: 'Encabezado 1',
      add_h2: 'Encabezado 2',
      add_h3: 'Encabezado 3',
      add_bullet: 'Lista con viñetas',
      add_number: 'Lista numerada',
      add_todo: 'Lista de tareas',
      list_item: 'Elemento de lista',
      todo_item: 'Tarea',
      last_edited: 'Última edición',
      tools: 'Herramientas',
      text: 'Texto',
      month: 'Mes',
      week: 'Semana',
      day: 'Día',
      today: 'Hoy',
      add_event: 'Añadir Evento',
      event_title: 'Título del Evento',
      duration: 'Duración',
      tags: 'Etiquetas',
      cancel: 'Cancelar',
      new_tag: 'Nueva Etiqueta',
      tag_name: 'Nombre de la etiqueta',
      save_label: 'Guardar',
      location: 'Ubicación',
      add_location: 'Añadir ubicación',
      all_day: 'Todo el día',
      add_description: 'Añadir descripción',
      create_event: 'Crear Evento',
      empty_day: 'Tu día está vacío',
      downtime_message: 'Tiempo de inactividad—recarga completa.',
      time_utilized_message: '¡Tiempo bien aprovechado!',
      two_hours_ago: 'hace 2h',
      quote: '"El secreto de salir adelante es comenzar."',
      author: '— Mark Twain'
    }
  },
  'Français': { 
    timezone: 'Central European Time (CET)',
    translations: {
      dashboard: 'Tableau de bord',
      tasks: 'Tâches',
      notes: 'Notes',
      calendar: 'Calendrier',
      settings: 'Paramètres',
      profile: 'Profil',
      security: 'Sécurité',
      language: 'Langue',
      save: 'Enregistrer',
      reset: 'Réinitialiser par Email',
      bio: 'Bio',
      name: 'Nom Complet',
      email: 'Adresse Email',
      email_readonly_hint: 'L’e-mail est lié à ta connexion et ne peut pas être modifié ici.',
      welcome: 'Bon retour, Alex',
      search: 'Rechercher',
      signout: 'Déconnexion',
      interface_lang: 'Langue de l\'interface',
      date_time: 'Date et Heure',
      timezone: 'Fuseau Horaire',
      timezone_sync: 'Le fuseau horaire est automatiquement synchronisé avec votre sélection de langue.',
      lang_update_note: 'La modification des paramètres de langue mettra à jour l\'ensemble de l\'interface. Certains contenus peuvent rester dans leur langue d\'origine.',
      good_morning: 'Bon matin',
      good_afternoon: 'Bon après-midi',
      good_evening: 'Bonsoir',
      start_focus: 'Démarrer une Session de Concentration',
      close_focus: 'Fermer la concentration',
      focus_session: 'Session de concentration',
      focus_session_hint: 'Choisis un mode, puis appuie sur lecture sur le minuteur quand tu es prêt.',
      today_agenda: 'Agenda d\'Aujourd\'hui',
      open_calendar: 'Ouvrir le Calendrier Complet',
      recent_notebooks: 'Cahiers Récents',
      view_library: 'Voir la Bibliothèque',
      productivity_tip: 'Conseil de Productivité Quotidien',
      tip_text: 'Révisez vos notes dans les 24 heures pour améliorer la rétention à long terme jusqu\'à 80%.',
      tasks_title: 'Tâches',
      tasks_subtitle: 'Organisez votre flux académique avec précision.',
      new_task: 'Nouvelle Tâche',
      todo: 'À Faire',
      started: 'Commencé',
      done: 'Terminé',
      add_task: 'Ajouter une Tâche',
      title: 'Titre',
      description: 'Description',
      due_date: 'Date d\'échéance',
      importance: 'Importance',
      create_task: 'Créer une Tâche',
      what_needs_done: 'Qu\'est-ce qui doit être fait ?',
      add_details: 'Ajouter des détails...',
      started_on: 'Commencé le',
      finished_on: 'Terminé le',
      notes_title: 'Notes',
      notes_subtitle: 'Organisez vos pensées et vos idées.',
      search_notes: 'Rechercher des notes...',
      recent_folders: 'Dossiers Récents',
      todays: 'Aujourd\'hui',
      this_week: 'Cette Semaine',
      this_month: 'Ce Mois',
      new_folder: 'Nouveau dossier',
      my_notes: 'Mes Notes',
      new_note: 'Nouvelle Note',
      notebooks: 'Cahiers',
      pages: 'Pages',
      manage_notebooks: 'Gérez vos cahiers et documents.',
      upload_pdf: 'Télécharger PDF',
      new_notebook: 'Nouveau Cahier',
      documents: 'Documents',
      no_notebooks: 'Aucun cahier dans ce dossier pour le moment.',
      untitled_page: 'Page sans titre',
      untitled_note: 'Note sans titre',
      delete_note_confirm: 'Êtes-vous sûr de vouloir supprimer cette note ?',
      delete_page_confirm: 'Êtes-vous sûr de vouloir supprimer cette page ?',
      delete_notebook_confirm: 'Êtes-vous sûr de vouloir supprimer ce cahier et toutes ses pages ?',
      enter_notebook_title: 'Entrez le nouveau titre du cahier :',
      type_something: 'Écrivez quelque chose...',
      add_image: 'Ajouter une Image',
      add_h1: 'Titre 1',
      add_h2: 'Titre 2',
      add_h3: 'Titre 3',
      add_bullet: 'Liste à puces',
      add_number: 'Liste numérotée',
      add_todo: 'Liste de tâches',
      list_item: 'Élément de liste',
      todo_item: 'Tâche',
      last_edited: 'Dernière modification',
      tools: 'Outils',
      text: 'Texte',
      month: 'Mois',
      week: 'Semaine',
      day: 'Jour',
      today: 'Aujourd\'hui',
      add_event: 'Ajouter un Événement',
      event_title: 'Titre de l\'Événement',
      duration: 'Durée',
      tags: 'Étiquettes',
      cancel: 'Annuler',
      new_tag: 'Nouvelle Étiquette',
      tag_name: 'Nom de l\'étiquette',
      save_label: 'Enregistrer',
      location: 'Emplacement',
      add_location: 'Ajouter un emplacement',
      all_day: 'Toute la journée',
      add_description: 'Ajouter une description',
      create_event: 'Créer l\'Événement',
      empty_day: 'Votre journée est vide',
      downtime_message: 'Temps d\'arrêt—recharge terminée.',
      time_utilized_message: 'Temps bien utilisé !',
      two_hours_ago: 'il y a 2h',
      quote: '"Le secret pour avancer, c\'est de commencer."',
      author: '— Mark Twain'
    }
  },
  'Deutsch': { 
    timezone: 'Central European Time (CET)',
    translations: {
      dashboard: 'Dashboard',
      tasks: 'Aufgaben',
      notes: 'Notizen',
      calendar: 'Kalender',
      settings: 'Einstellungen',
      profile: 'Profil',
      security: 'Sicherheit',
      language: 'Sprache',
      save: 'Speichern',
      reset: 'Per E-Mail zurücksetzen',
      bio: 'Bio',
      name: 'Vollständiger Name',
      email: 'E-Mail-Adresse',
      email_readonly_hint: 'Die E-Mail ist mit deinem Login verknüpft und kann hier nicht geändert werden.',
      welcome: 'Willkommen zurück, Alex',
      search: 'Suche',
      signout: 'Abmelden',
      interface_lang: 'Oberflächensprache',
      date_time: 'Datum & Uhrzeit',
      timezone: 'Zeitzone',
      timezone_sync: 'Die Zeitzone wird automatisch mit Ihrer Sprachauswahl synchronisiert.',
      lang_update_note: 'Das Ändern der Spracheinstellungen aktualisiert die gesamte Benutzeroberfläche. Einige Inhalte bleiben möglicherweise in ihrer Originalsprache.',
      good_morning: 'Guten Morgen',
      good_afternoon: 'Guten Tag',
      good_evening: 'Guten Abend',
      start_focus: 'Fokus-Sitzung Starten',
      close_focus: 'Fokus schließen',
      focus_session: 'Fokus-Sitzung',
      focus_session_hint: 'Wähle einen Modus und drücke auf dem Timer auf Play, wenn du bereit bist.',
      today_agenda: 'Heutige Agenda',
      open_calendar: 'Vollständigen Kalender Öffnen',
      recent_notebooks: 'Aktuelle Notizbücher',
      view_library: 'Bibliothek Anzeigen',
      productivity_tip: 'Täglicher Produktivitätstipp',
      tip_text: 'Überprüfen Sie Ihre Notizen innerhalb von 24 Stunden, um die langfristige Merkfähigkeit um bis zu 80% zu verbessern.',
      tasks_title: 'Aufgaben',
      tasks_subtitle: 'Organisieren Sie Ihren akademischen Ablauf mit Präzision.',
      new_task: 'Neue Aufgabe',
      todo: 'Zu Erledigen',
      started: 'Begonnen',
      done: 'Erledigt',
      add_task: 'Aufgabe Hinzufügen',
      title: 'Titel',
      description: 'Beschreibung',
      due_date: 'Fälligkeitsdatum',
      importance: 'Wichtigkeit',
      create_task: 'Aufgabe Erstellen',
      what_needs_done: 'Was muss getan werden?',
      add_details: 'Details hinzufügen...',
      started_on: 'Begonnen am',
      finished_on: 'Abgeschlossen am',
      notes_title: 'Notizen',
      notes_subtitle: 'Organisieren Sie Ihre Gedanken und Ideen.',
      search_notes: 'Notizen suchen...',
      recent_folders: 'Aktuelle Ordner',
      todays: 'Heute',
      this_week: 'Diese Woche',
      this_month: 'Diesen Monat',
      new_folder: 'Neuer Ordner',
      my_notes: 'Meine Notizen',
      new_note: 'Neue Notiz',
      notebooks: 'Notizbücher',
      pages: 'Seiten',
      manage_notebooks: 'Verwalten Sie Ihre Notizbücher und Dokumente.',
      upload_pdf: 'PDF Hochladen',
      new_notebook: 'Neues Notizbuch',
      documents: 'Dokumente',
      no_notebooks: 'Noch keine Notizbücher in diesem Ordner.',
      untitled_page: 'Unbenannte Seite',
      untitled_note: 'Unbenannte Notiz',
      delete_note_confirm: 'Sind Sie sicher, dass Sie diese Notiz löschen möchten?',
      delete_page_confirm: 'Sind Sie sicher, dass Sie diese Seite löschen möchten?',
      delete_notebook_confirm: 'Sind Sie sicher, dass Sie dieses Notizbuch und alle seine Seiten löschen möchten?',
      enter_notebook_title: 'Neuen Notizbuchtitel eingeben:',
      type_something: 'Schreiben Sie etwas...',
      add_image: 'Bild hinzufügen',
      add_h1: 'Überschrift 1',
      add_h2: 'Überschrift 2',
      add_h3: 'Überschrift 3',
      add_bullet: 'Aufzählungsliste',
      add_number: 'Nummerierte Liste',
      add_todo: 'Aufgabenliste',
      list_item: 'Listenelement',
      todo_item: 'Aufgabe',
      last_edited: 'Zuletzt bearbeitet',
      tools: 'Werkzeuge',
      text: 'Text',
      month: 'Monat',
      week: 'Woche',
      day: 'Tag',
      today: 'Heute',
      add_event: 'Ereignis hinzufügen',
      event_title: 'Ereignistitel',
      duration: 'Dauer',
      tags: 'Tags',
      cancel: 'Abbrechen',
      new_tag: 'Neuer Tag',
      tag_name: 'Tag-Name',
      save_label: 'Speichern',
      location: 'Ort',
      add_location: 'Ort hinzufügen',
      all_day: 'Ganztägig',
      add_description: 'Beschreibung hinzufügen',
      create_event: 'Ereignis erstellen',
      empty_day: 'Dein Tag ist leer',
      downtime_message: 'Auszeit—Aufladen abgeschlossen.',
      time_utilized_message: 'Zeit gut genutzt!',
      two_hours_ago: 'vor 2 Std.',
      quote: '"Das Geheimnis des Vorwärtskommens besteht darin, den ersten Schritt zu tun."',
      author: '— Mark Twain'
    }
  },
  '日本語': { 
    timezone: 'Japan Standard Time (JST)',
    translations: {
      dashboard: 'ダッシュボード',
      tasks: 'タスク',
      notes: 'ノート',
      calendar: 'カレンダー',
      settings: '設定',
      profile: 'プロフィール',
      security: 'セキュリティ',
      language: '言語',
      save: '変更を保存',
      reset: 'メールでリセット',
      bio: '自己紹介',
      name: '氏名',
      email: 'メールアドレス',
      email_readonly_hint: 'メールアドレスはログインに紐づいており、ここでは変更できません。',
      welcome: 'おかえりなさい、Alex',
      search: '検索',
      signout: 'サインアウト',
      interface_lang: 'インターフェース言語',
      date_time: '日付と時刻',
      timezone: 'タイムゾーン',
      timezone_sync: 'タイムゾーンは言語の選択に合わせて自動的に同期されます。',
      lang_update_note: '言語設定を変更すると、インターフェース全体が更新されます。一部のコンテンツは元の言語のまま残る場合があります。',
      good_morning: 'おはようございます',
      good_afternoon: 'こんにちは',
      good_evening: 'こんばんは',
      start_focus: '集中セッションを開始',
      close_focus: '集中を閉じる',
      focus_session: '集中セッション',
      focus_session_hint: 'モードを選び、準備ができたらタイマーの再生を押してください。',
      today_agenda: '今日の予定',
      open_calendar: 'カレンダーを開く',
      recent_notebooks: '最近のノート',
      view_library: 'ライブラリを表示',
      productivity_tip: '今日のヒント',
      tip_text: '24時間以内にノートを見直すと、長期的な記憶保持率が最大80%向上します。',
      tasks_title: 'タスク',
      tasks_subtitle: 'アカデミックなフローを正確に整理しましょう。',
      new_task: '新しいタスク',
      todo: '未完了',
      started: '進行中',
      done: '完了',
      add_task: 'タスクを追加',
      title: 'タイトル',
      description: '説明',
      due_date: '期限',
      importance: '重要度',
      create_task: 'タスクを作成',
      what_needs_done: '何をすべきですか？',
      add_details: '詳細を追加...',
      started_on: '開始日',
      finished_on: '完了日',
      notes_title: 'ノート',
      notes_subtitle: '考えやアイデアを整理しましょう。',
      search_notes: 'ノートを検索...',
      recent_folders: '最近のフォルダー',
      todays: '今日',
      this_week: '今週',
      this_month: '今月',
      new_folder: '新しいフォルダー',
      my_notes: 'マイノート',
      new_note: '新しいノート',
      notebooks: 'ノートブック',
      pages: 'ページ',
      manage_notebooks: 'ノートブックとドキュメントを管理します。',
      upload_pdf: 'PDFをアップロード',
      new_notebook: '新しいノートブック',
      documents: 'ドキュメント',
      no_notebooks: 'このフォルダーにはまだノートブックがありません。',
      untitled_page: '無題のページ',
      untitled_note: '無題のノート',
      delete_note_confirm: 'このノートを削除してもよろしいですか？',
      delete_page_confirm: 'このページを削除してもよろしいですか？',
      delete_notebook_confirm: 'このノートブックとそのすべてのページを削除してもよろしいですか？',
      enter_notebook_title: '新しいノートブックのタイトルを入力してください：',
      type_something: '何か入力してください...',
      add_image: '画像を追加',
      add_h1: '見出し 1',
      add_h2: '見出し 2',
      add_h3: '見出し 3',
      add_bullet: '箇条書きリスト',
      add_number: '番号付きリスト',
      add_todo: 'ToDoリスト',
      list_item: 'リスト項目',
      todo_item: 'ToDo項目',
      last_edited: '最終編集',
      tools: 'ツール',
      text: 'テキスト',
      month: '月',
      week: '週',
      day: '日',
      today: '今日',
      add_event: 'イベントを追加',
      event_title: 'イベントのタイトル',
      duration: '期間',
      tags: 'タグ',
      cancel: 'キャンセル',
      new_tag: '新しいタグ',
      tag_name: 'タグ名',
      save_label: '保存',
      location: '場所',
      add_location: '場所を追加',
      all_day: '終日',
      add_description: '説明を追加',
      create_event: 'イベントを作成',
      empty_day: '今日の予定はありません',
      downtime_message: 'ダウンタイム—リチャージ完了。',
      time_utilized_message: '時間を有効活用できました！',
      two_hours_ago: '2時間前',
      quote: '「前進するための秘訣は、まず始めることだ」',
      author: '— マーク・トウェイン'
    }
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLangState] = useState<Language>('English (US)');

  const setLanguage = (lang: Language) => {
    setLangState(lang);
  };

  const t = (key: string) => {
    return LANGUAGE_CONFIG[language].translations[key] || key;
  };

  const timezone = LANGUAGE_CONFIG[language].timezone;

  return (
    <LanguageContext.Provider value={{ language, timezone, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
